apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vulnapp-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: vulnapp-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.domain }}
