gitea:
  config:
    database:
      DB_TYPE: postgres
      HOST: gitea-postgres-postgresql.gitea.svc.cluster.local:5432
      NAME: postgres
      USER: postgres
      PASSWD: fTQVhNPJyy
    cache:
      ADAPTER: redis
      HOST: gitea-redis-master.gitea.svc.cluster.local:6379
      PASSWORD: 7DU4L8hm0R

postgresql:
  enabled: false  # Disable the bundled PostgreSQL

postgresql-ha:
  enabled: false

redis:
  enabled: false  # Disable the bundled Redis

redis-cluster:
  enabled: false