redis:
  enabled: true
  global:
    redis:
      password: gitea
  auth:
    password: gitea
  master:
    service:
      port: 6379
  replica:
    replicaCount: 0

postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  persistence:
    size: 10Gi

redis-cluster:
  enabled: false

postgresql-ha:
  enabled: false