apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vulnapp-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@vulnapp.dev
    privateKeySecretRef:
      name: vulnapp-cert-issuer-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-token
            key: token